INSERT INTO category (category_id, name) VALUES ('b4c63102-5286-498a-bc5b-e7f6e2c93b11', 'SuperCategoria');
INSERT INTO category (category_id, name) VALUES ('a373633c-1bd1-4b80-8ea5-7568baadce87', 'Ebooks - Action/Adventure');
INSERT INTO category (category_id, name) VALUES ('88ab2979-341f-41ca-bbea-fcddcd98b276', 'Ebooks - Art');
INSERT INTO category (category_id, name) VALUES ('b7c558ad-2ff9-4a12-8f7f-5ae3af1a5c5b', 'Ebooks - Biographical');
INSERT INTO category (category_id, name) VALUES ('b71ce88b-704b-4416-b012-bd08dd701543', 'Ebooks - Business');
INSERT INTO category (category_id, name) VALUES ('c3c45c9f-b869-4d23-85a8-a879e3654649', 'Ebooks - Comics/Graphic Novels');
INSERT INTO category (category_id, name) VALUES ('96101239-390c-4c80-a8b0-b2445501bb36', 'Ebooks - Computer/Internet');
INSERT INTO category (category_id, name) VALUES ('e5162267-89e2-4251-b4ea-d8a3fd68cd3b', 'Ebooks - Crafts');
INSERT INTO category (category_id, name) VALUES ('7cf6c669-e67b-41c7-b776-35817d324439', 'Ebooks - Crime/Thriller');
INSERT INTO category (category_id, name) VALUES ('5ca0023b-553a-4053-8814-362d3a188e1f', 'Ebooks - Fantasy');
INSERT INTO category (category_id, name) VALUES ('d5a8baa3-358e-4cb5-b7d9-c4adb6063651', 'Ebooks - Food');
INSERT INTO category (category_id, name) VALUES ('4b9c341b-1001-45df-9f62-01f7b0b50b37', 'Ebooks - General Fiction');
INSERT INTO category (category_id, name) VALUES ('7fea285a-d5c5-4f23-a7d2-459c90f596e9', 'Ebooks - General Non-Fiction');
INSERT INTO category (category_id, name) VALUES ('f102af30-fcf2-4a8f-bc9e-66f36923e001', 'Ebooks - Historical Fiction');
INSERT INTO category (category_id, name) VALUES ('bfb60ec1-5f0c-4861-ac0e-2a69cc411396', 'Ebooks - History');
INSERT INTO category (category_id, name) VALUES ('2318584c-c1aa-4dbf-8c12-e848a254aada', 'Ebooks - Home/Garden');
INSERT INTO category (category_id, name) VALUES ('2425592f-044f-4ced-9fde-0ae45f4995c5', 'Ebooks - Horror');
INSERT INTO category (category_id, name) VALUES ('d3526e98-6c8a-4972-82bc-fa2fac06e6cd', 'Ebooks - Humor');
INSERT INTO category (category_id, name) VALUES ('1642d26c-4d47-444a-8bcb-63b1d1455b52', 'Ebooks - Illusion/Magic');
INSERT INTO category (category_id, name) VALUES ('6c619117-b941-4c47-9ed5-873cb647adcf', 'Ebooks - Instructional');
INSERT INTO category (category_id, name) VALUES ('c70449c1-d193-4622-ae88-f1d6e0770637', 'Ebooks - Juvenile');
INSERT INTO category (category_id, name) VALUES ('cd6ab2cf-eedf-47ef-bbe2-5ed3523bfb29', 'Ebooks - Language');
INSERT INTO category (category_id, name) VALUES ('0a2b9eaf-3bbb-4ea3-987a-bd0d7d97e807', 'Ebooks - Literary Classics');
INSERT INTO category (category_id, name) VALUES ('900de15f-e73e-470e-b897-47375e2077a3', 'Ebooks - Magazines/Newspapers');
INSERT INTO category (category_id, name) VALUES ('3aaa5421-dbd3-4b3f-96e3-0ee19b112377', 'Ebooks - Math/Science/Tech');
INSERT INTO category (category_id, name) VALUES ('03a75c42-690f-47d9-bd2d-9abc01c57703', 'Ebooks - Medical');
INSERT INTO category (category_id, name) VALUES ('3a3e9b1a-a7cf-4ac4-8ff2-a44c46a90ba4', 'Ebooks - Mixed Collections');
INSERT INTO category (category_id, name) VALUES ('76b8aa6a-2200-4562-8374-d392f05bd4f7', 'Ebooks - Mystery');
INSERT INTO category (category_id, name) VALUES ('2586cee8-a5c0-420c-8905-f274a0be2ddb', 'Ebooks - Nature');
INSERT INTO category (category_id, name) VALUES ('d4210222-3e00-4798-881d-6cf06f144e9e', 'Ebooks - Philosophy');
INSERT INTO category (category_id, name) VALUES ('52b59752-41f0-4e5b-aafe-478745f4cbd8', 'Ebooks - Pol/Soc/Relig');
INSERT INTO category (category_id, name) VALUES ('9df69641-fa3b-41de-8abe-4fc29b59b797', 'Ebooks - Recreation');
INSERT INTO category (category_id, name) VALUES ('179e5a37-0169-4726-87fc-3cbccdb47c35', 'Ebooks - Romance');
INSERT INTO category (category_id, name) VALUES ('27b4dda0-d0ec-4b36-8f08-9f16dc8f6ba5', 'Ebooks - Science Fiction');
INSERT INTO category (category_id, name) VALUES ('b641e695-7f5a-408d-8030-f1c293d3c195', 'Ebooks - Self Help');
INSERT INTO category (category_id, name) VALUES ('9355a36d-f8cd-450a-b834-985bf83bf703', 'Ebooks - Travel/Adventure');
INSERT INTO category (category_id, name) VALUES ('c1146e0d-e51c-4587-ac93-e718071da8f5', 'Ebooks - True Crime');
INSERT INTO category (category_id, name) VALUES ('9b91ea44-6dde-44e5-82db-2fbd42ce4dd7', 'Ebooks - Urban Fantasy');
INSERT INTO category (category_id, name) VALUES ('d7203713-7b02-41d0-962c-22ff80c68c14', 'Ebooks - Western');
INSERT INTO category (category_id, name) VALUES ('c9db5614-bb86-4bac-850e-0a09af9e224e', 'Ebooks - Young Adult');

INSERT INTO users (id, username, password, full_name, email, avatar, account_non_expired, account_non_locked, credentials_non_expired, enabled, creation_date) VALUES ('1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'admin', '{bcrypt}$2a$12$1hfnQew5F5qsdr5u/qbIze7/jt1asO58g8YmxJZeIKew8gWnYyyky', 'admin admin', 'admin@admin.admin', '', true, true, true, true, '2022-02-01');
INSERT INTO user_roles(user_id, roles) VALUES ('1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 2);

INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('80f707ff-d099-4b2a-afd2-b9f27e5a091c', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'European_Armour_(1958).pdf', 'European Armour: c.1066-c.1700', 'Claude Blair', 'A seminal work in the research of European armour by one of the foremost experts of the 20th century on the topic, Claude Blair.  Not heavily illustrated but the information is still quite valid.  If you want an online review of the book Matt Easton of Scholagladiatoria https://www.youtube.com/watch?v=fDe10pRiGIM');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('34d815d2-0b3c-4fe9-a806-6154f22f4603', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'Medieval_Weapons_An_Illustrated_History_of_Their_Impact.pdf', 'Medieval Weapons: An Illustrated History of Their Impact', 'Kelly DeVries, Robert Douglas Smith', 'This fascinating reference covers the weapons and armor used by warriors from the 4th to the 15th century and discusses how and why they changed over time. • Narrative chapters follow the development of medieval weapons and armor in four periods: early medieval (376–750), Carolingian (750–1050), the Crusades (1050–1300), and late medieval (1300–1550) • The chronological reference section features vivid illustrations of representative swords, bows, cudgels, shields, and increasingly more sophisticated armor');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('576cad41-c7cb-4a1f-834d-921eb3ebdfd2', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'Arms_and_Armour_of_the_Medieval_Knight.pdf', 'Arms & Armour of the Medieval Knight', 'David Edge', 'A brilliant, highly illustrated survey of the real story of knights & their weapons & the often far from chivalrous wars & battles they fought. For generations the devastating charging power of mounted knights dominated the military affairs of Europe but throughout the medieval period weapons & armor were evolving constantly, & a variety of styles developed. This story is traced from the early days of chain mail & crude helmets to the vastly expensive & elaborate suits of full plate armor of the 15th & 16th cent. Includes 170 B&W & 150 color illus., with many unpublished photos & specially commissioned artwork. Glossary of terms. Details of the construction of armor.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('c73f8dac-2b95-47c0-a46c-5f2ceaee7962', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, '(Aspects of Greek and Roman Life) Anthony M. Snodgrass - Arms and Armour of the Greeks-Cornell University Press (1967).pdf', 'Arms and Armour of the Greeks', 'Anthony M Snodgrass', '"Snodgrass book on Greek arms and armour must rank already as a standard textbook... It is as clear as any book can be on a surprisingly ill-documented subject."--Economist"Helps to explain why (for one thing) the Greeks won the Persian Wars and how they then stuck for centuries, with true military unimaginativeness, to their far from enterprising hoplite phalanx tactics."--Times Literary Supplement. In 490 B.C. a force of some 10,000 Athenians and their allies met a much larger Persian army on the rocky beach at Marathon. The Greeks arrayed themselves in a thin line, advancing on the Persians slowly, then breaking into a run, splitting the center and enfolding the Persian army in their wings. The tactic surprised the Persians, and even some Greeks. But, argues Cambridge University archaeologist A.M. Snodgrass, tactical innovation alone did not carry the day. "We shall never know quite how Marathon was won," he writes, but "the superiority of Greek equipment must have been an important factor here and elsewhere, and at times perhaps a decisive one."The Greeks, in short, were better armed than the Persians, an edge that had evolved over centuries of martial experimentation. Snodgrass traces the development of armor and weapons and the use of adjuncts like cavalry and war dogs through Greek history, from Mycenaean times to the age of Alexander. He notes, gainsaying many other military historians of ancient Greece, that the Greeks were nowhere near as effective in using cavalry as were their opponents, Persian and otherwise; even in Alexander''s time, he writes, cavalry was neglected in favor of mass infantry attacks from heavily armed phalanxes--a tactic that must have cost many lives, but that surely put an unholy fear in the Greeks'' enemies. Snodgrass''s slender volume is a useful companion for students of Herodotus, Xenophon, Homer, and other chroniclers of ancient warfare.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('87ca377f-76b5-4e2c-aeba-2f86def2a2bf', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'Encountering_Medieval_Textiles_and_Dress.pdf', 'Encountering Medieval Textiles and Dress: Objects, Texts, Images', 'D Koslin, Janet Snyder', '"An outstanding series of essays by historians, art historians, and literary specialists on a wide variety of topics in medieval textiles, from manufacture and use, to style, fashion, iconography, and the many shades of social meaning." - William W. Clark, Queens College and the Graduate Center, CUNY."This volume demonstrates the wide variety of excellent new work now being done on dress and costume history. The papers are rich in content and cover a wide variety of periods and subject matter." - Jonathan J. G. Alexander, Institute of Fine Arts, New York University. "The volume is a valuable addition to both the library of a general reader and a costume historian. For the general reader the books provides ready access to information ranging over a six-hundred year period. For the costume historian there is a wealth of detailed information to add breadth and depth to one''s knowledge, with an additional resource of information in the form of copious endnotes and bibliographic references." - Sandra L. Rosenbau, Dress. In this wide-ranging study of costume history contributors explore fashion, textiles, and the representation of clothing in the middle ages. Essays combine the perspectives of archaeology, art history, economics, religion, costume history, material culture, and literary criticism and explore materials from England, France, the Low Countries, Scandinavia, Germany, Italy, and Ireland. The collection focuses on multiple aspects of textiles and dress - their making, meaning, and representation - and explores the impact of international trade and other forms of cultural exchange.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('49616fc2-5ffd-4141-9d43-0d4e40f94ea8', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'European Weapons and Armour_ Fr - Ewart Oakeshott.pdf', 'European Weapons and Armour: From the Renaissance to the Industrial Revolution', 'Ewart Oakeshott', 'A treasury of information based on solid scholarship, anyone seeking a factual and vivid account of the story of arms from the Renaissance period to the Industrial Revolution will welcome this book. The author chooses as his starting-point the invasion of Italy by France in 1494, which sowed the dragon''s teeth of all the successive European wars; the French invasion was to accelerate the trend towards new armaments and new methods of warfare. The author describes the development of the handgun and the pike, the use and style of staff-weapons, mace and axe and war-hammer, dagger and dirk and bayonet. He shows how armour attained its full Renaissance splendour and then suffered its sorry and inevitable decline, culminating in the Industrial Revolution, with its far-reaching effects on military armaments. Above all, he follows the long history of the sword, queen of weapons, to the late eighteenth century, when it finally ceased to form a part of a gentleman''s every-day wear.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('19e557dc-3d07-4f87-91d9-90be3964ec09', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'From_Medieval_Manuscript_to_Modern_Practice_The_Longsword_Techniques_of_Fiore_Dei_Liberi.pdf', 'From Medieval Manuscript to Modern Practice: The Longsword Techniques of Fiore dei Liberi', 'Guy Windsor', 'In From Medieval Manuscript to Modern Practice, renowned historical swordsman Guy Windsor demystifies one of the greatest martial arts books of all time, Fiore dei Liberi''s Il Fior di Battaglia (The Flower of Battle).In the late 14th century dei Liberi, an Italian knightly combat master, wrote Il Fior di Battaglia (The Flower of Battle). This magnificent, illustrated manuscript described how to fight on foot and on horseback, in armour and without, with sword, spear, pollax, dagger, or with no weapon at all. Windsor spent the last twenty years studying Fiore''s work and creating a modern practice of historical swordsmanship from it. In this book, Windsor takes you through all of Fiore''s longsword techniques on foot without armour. Each technique (or “play”) is shown with the drawing from the treatise, Windsor''s transcription and translation of the text, his commentary on how it fits into the system and works in practice, and a link to a video of the technique in action. The book also contains a detailed introduction describing Fiore''s life and times, and extensive discussion of the contexts in which Fiore''s art belongs. From Medieval Manuscript to Modern Practice is essential reading for all martial artists and historians of the medieval and early Renaissance.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('65d3309e-e1f4-4eae-8802-f4982c1cb68c', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'Hafted_Weapons_in_Medieval_and_Renaissance_Europe .pdf', 'Hafted Weapons in Medieval and Renaissance Europe: The Evolution of European Staff Weapons between 1200 and 1650', 'John Waldman', 'The development treated in this volume of a variety of staff weapons in the Medieval and Renaissance periods in Europe is of importance, as the repeated success of their use caused substantive political changes. Their typology, use, and smithing techniques as well as correlations with contemporary artistic renditions, are discussed in great detail. Surviving specimens from museums and collections throughout the Western Hemisphere are used. Conservation issues are also dealt with. The book is heavily illustrated with black and white, color photographs and drawings and has a foreword by Walther Karcheski, Chief Curator of Arms and Armor of the Frazier Antique Arms Museum. It is intended as a reference for historical scholars, artists, museum curators, private collectors and the art market, and is a timely clarification of the nature of these arms.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('465fc023-dafc-4813-85ef-16c19d77a5f6', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'Knights_Chivalry_and_Violence .pdf', 'Knights: Chivalry and Violence', 'John Sadler, Rosie Serdiville', 'Originally warriors mounted on horseback, knights became associated with the concept of chivalry as it was popularised in medieval European literature. Knights were expected to fight bravely and honourably and be loyal to their lord until death if necessary. Later chivalry came to encompass activities such as tournaments and hunting, and virtues including justice, charity and faith. The Crusades were instrumental in the development of the code of chivalry, and some crusading orders of knighthood, such as the Knights Templar, have become legend. Boys would begin their knightly training at the age of seven, learning to hunt and studying academic studies before becoming assistants to older knights, training in combat and learning how to care for a knight’s essentials: arms, armour, and horses. After fourteen years of training, and when considered master of all the skills of knighthood, a squire was eligible to be knighted. In peacetime knights would take part in tournaments. Tournaments were a major spectator sport, but also an important way for knights to practice their skills – knights were often injured and sometimes killed in melees. Knights figured large in medieval warfare and literature. In the 15th century knights became obsolete due to advances in warfare, but the title of ‘knight’ has survived as an honorary title granted for services to a monarch or country, and knights remain a strong concept in popular culture. This short history will cover the rise and decline of the medieval knights, including the extensive training, specific arms and armour, tournaments and the important concept of chivalry. Review: “It’s a really informative book which won’t wear out its welcome. It whets the appetite to learn more, which is really the greatest compliment I can give it.” (Army Rumour Service). About the Authors: John Sadler is a military historian born and living in Northumberland. He has written extensively on a range of periods and is a battlefield tour guide who covers most of the major battles from both world wars (and numerous others). He also lectures on military history at Newcastle University’s Centre for Lifelong Learning, is a Fellow of the Royal Historical Society and the Society of Antiquaries of Scotland, a member of the Battlefield Trust and Guild of Battlefield Tour Guides. Rosie Serdiville is a social historian and re-enactor with a particular interest in the wider impact of war on civilian populations. She delights in spending time in archives: some of the most interesting characters in this volume have emerged from archival materials.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('efb80d1e-c904-49cb-b037-af3cfa95ba04', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'Knives_and_Scabbards.pdf', 'Knives and Scabbards', 'J Cowgill, M de Neergaard, N Griffiths', 'Knives were vital to medieval man for a whole range of uses, from the domestic to the wider social context: Anglo-Saxon pre-Christian burials bear silent witness to this dependence in the many cases where knives are found among the grave-goods. Forged and hafted with great skill, sometimes with elaborately decorated scabbards, knives are of intrinsic fascination, besides being indicators of the popular artistic tastes of the time. This book catalogues, discusses and illustrates over five hundred knives, scabbards, shears and scissors dating from the mid-12th to the mid-15th centuries and found in the City of London, particularly along the waterfront sites, where recovered items can be accurately dated by dendrochronology and coin finds. It is a fundamental work of reference for medieval artefacts and material culture, an essential handbook for excavators all over Britain and much of Europe. JANE COWGILL, MARGRETHE DE NEERGAARDE and NICK GRIFFITHS are former members of the staff of the Museum of London.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('41b8d91f-dae0-4f83-9efd-5fcc5bf51280', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'Lorica_Segmentata_Volume_I_A_Handbook_of_Articulated_Roman_Plate_Armour.pdf', 'Lorica Segmentata: A handbook of articulated Roman plate armour. Vol. 1', 'M C Bishop', 'This in-depth examination of articulated Roman plate armour contains a detailed discussion of all the significant evidence including previously unpublished material. It looks at each of the principle types of articulated plate armour, using photographs and drawings of original finds alongside full-sized and specially-prepared computer-generated reconstructions. It also examines the strengths and weaknesses of this form of armour, considering a wide range of technical details, as well as practical aspects relating to its reproduction.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('9a985675-b79e-4ec9-a06f-5e6ccee83e7e', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'Roman_Military_Equipment_From_the_Punic_Wars_to_the_Fall_of_Rome.pdf', 'Roman Military Equipment from the Punic Wars to the Fall of Rome', 'M C Bishop, J C Coulston', 'Rome''s rise to empire is often said to have owed much to the efficiency and military skill of her armies and their technological superiority over barbarian enemies. But just how ''advanced'' was Roman military equipment? What were its origins and how did it evolve? The authors of this book have gathered a wealth of evidence from all over the Roman Empire''s excavated examples as well as pictorial and documentary sources to present a picture of what range of equipment would be available at any given time, what it would look like and how it would function. They examine how certain pieces were adopted from Rome''s enemies and adapted to particular conditions of warfare prevailing in different parts of the Empire. They also investigate in detail the technology of military equipment and the means by which it was produced, and discuss wider questions such as the status of the soldier in Roman society. Both the specially prepared illustrations and the text have been completely revised for the second edition of this detailed and authoritative handbook, bringing it up to date with the very latest research. It illustrates each element in the equipment of the Roman soldier, from his helmet to his boots, his insignia, his tools and his weapons. This book will appeal to archaeologists, ancient and military historians as well as the generally informed and inquisitive reader.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('54409f56-87b8-43ea-ad26-92e3f44284d7', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', 'bfb60ec1-5f0c-4861-ac0e-2a69cc411396', '2022-02-05', false, 0, 'The_Longbow-Osprey_Publishing.pdf', 'The Longbow', 'Mike Loades', 'Boasting a rate of shooting not seen again in English hands until the late 19th century, the longbow was the weapon at the heart of the English military ascendancy in the century after 1340. Capable of subjecting the enemy to a hail of deadly projectiles, the longbow in the hands of massed archers made possible the extraordinary victories enjoyed by English forces over superior numbers at Crécy and Poitiers, and remained an important battlefield weapon throughout the Wars of the Roses and beyond; it also played a leading role in raiding, siege and naval warfare. Its influence and use spread to the armies of Burgundy, Scotland and other powers, and its reputation as a cost-effective and easily produced weapon led to calls for its widespread adoption in the nascent armies of the American Republic as late as the 1770s.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('a6525ba7-07d2-4ff6-93c5-62ae121fd1ed', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', '6c619117-b941-4c47-9ed5-873cb647adcf', '2022-02-05', false, 0, 'Basic_Armouring_A_practical_Introduction_to_Armour_Making.pdf', 'Basic Armouring: A Practical Introduction to Armour Making, 2nd edition', 'John Blackwell', 'This booklet is a primer who want to make their own simple, practical armour.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('88313a2a-7901-4118-8383-5685ca13fb6a', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', '6c619117-b941-4c47-9ed5-873cb647adcf', '2022-02-05', false, 0, 'Engraving_on_Precious_Metals.pdf', 'Engraving on Precious Metals', 'A Brittain, P Morton', 'Engraving by hand is the oldest art of mankind and one that still flourishes today. With a simple message the precious metal engraver can give a unique personality to an otherwise commonplace cigarette box, goblet or compact. Despite the singular character of the craft very few practical books have been written on engraving precious and other materials employed by the jeweller; in fact none have been published in the United Kingdom for many years. "Engraving on Precious Metals" is for professionals and others who wish to learn hand engraving as a hobby or trade, and reveals many previously undisclosed practices of the commercial engraver which help to make his skill quite astonishing. All aspects of the craft are covered exhaustively, including the relatively modern innovation of the high-class machine engraver. This machine is particularly useful for repeat monograms and designs which are afterwards filled, because the template that guides the machine can be cut by hand. Illustrated throughout with over 250 drawings, the book gives practical hints for use in the workshop, while artistic matters are covered extensively in chapters on lettering design and layout, monograms, nameplates and ornamentation. A basic knowledge of ancillary crafts can be found in the sections on piercing, polishing, soldering and inlaying, and the use of unusual materials such as ivory, wood or plastic is also discussed. The final chapter contains a wide selection of different styles of lettering which are numbered for easy reference, and can be used by the retailer to indicate styles to customers and engravers.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('c704366c-8efb-40d1-94b3-b7b3a382556d', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', '6c619117-b941-4c47-9ed5-873cb647adcf', '2022-02-05', false, 0, 'The_Art_of_Engraving.pdf', 'The Art of Engraving: A Book of Instructions', 'James B Meek', 'A magnificent, deluxe book with nearly 1400 photos, drawings and designs. Many are concerned with gun engraving but the techniques can be universally applied. This is an instant classic on which no effort was spared. This beautiful book gives you complete instruction in the art of engraving. The author spent seven years creating this unsurpassed resource for hand engraving. It is a supremely unique book, for not only does it sweep aside the mystery which has surrounded engraving through the centuries, but it factually, simply and in layman''s terms tells you how to engrave. Unlike so many so-called "instruction manuals", The Art of Engraving does not assume you know anything about engraving. You start at the beginning by learning to draw scrolls and layouts, then cut practice plates until you are sure enough of your ability to actually proceed to designing a pattern, transferring it to your piece and cutting it into the steel. Whether you want to learn to engrave now . . . think you might like to in the future . . . or simply wish to broaden your knowledge of the art to be able to better judge the work of others (as you will learn to tell the good from the bad - and know why), this is the book for you. Every gunsmith, bladesmith, metalsmith or craftsman - no matter what his other calling - has the soul of an artist. This personal, creative urge can be easily directed into the highly remunerative field of engraving through the coaching, no-nonsense instructions and technical support in The Art of Engraving.. Hundreds of original engravings, designs and layouts by the author (plus samples from other master engravers) to explain specific points and techniques. 208 extremely handsome 8½" x 11" pages. Over 1378 photographs, drawings, designs, layouts and illustrations. Deluxe, hardbound cloth covers. Bound a special way to lie flat. Printed on finest, dull-finished, coated paper available.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('5fce02ec-5479-4d6f-9dd1-4a9b08a44f9f', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', '6c619117-b941-4c47-9ed5-873cb647adcf', '2022-02-05', false, 0, 'The_Pattern-Welded_Blade.pdf', 'The Pattern-Welded Blade', 'Jim Hrisoulas', 'Pattern-welded blades are among the most beautiful and durable creations to emerge from the bladesmith''s forge. Now, Jim Hrisoulas, author of The Complete Bladesmith, reveals the secrets of this ancient craft, from the welding of the starting billet to final assembly of the completed blade. Learn basic patterns and stunning, complex designs.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('a590d6a2-b255-4764-9aff-42e76c1c274c', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', '3aaa5421-dbd3-4b3f-96e3-0ee19b112377', '2022-02-05', false, 0, 'KNIFE_Metallurgy_of_Steel_for_Bladesmiths_and_Others_who_Heat_Treat_and_Forge_Steel.pdf', 'Metallurgy of Steel for Bladesmiths & Others who Heat Treat and Forge Steel', 'John D Verhoeven', 'For the past 15 years or so I have been working with practicing bladesmiths on problems related to forging and heat treating steel blades. It has become apparent to me in that time that there is a need for a book that explains the metallurgy of steel for people who heat treat and forge steels and have had no formal metallurgical education.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('8366adbf-2685-428e-877a-2d2d7b53fc5f', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', '3aaa5421-dbd3-4b3f-96e3-0ee19b112377', '2022-02-05', false, 0, 'The_Master_Bladesmith_Advanced_Studies_in_Steel.pdf', 'The Master Bladesmith: Advanced Studies In Steel', 'Jim Hrisoulas', 'This advanced study of steel reveals forging secrets that for centuries have been protected by guilds. Never-before-seen instructions, diagrams and photos explain the tricks behind using Japanese mokume gane, differential heat treating, power hammers, and other techniques to make kukris, wavy blades, spears and swords that bear the master''s mark.');
INSERT INTO book(book_id, user_id, category_id, upload_date, vip, amount_downloads, book, title, author, description) VALUES ('a46568a5-4940-4bad-af26-ff9f905026f9', '1ed3d641-b9e8-4a8b-bf13-f6caef2e36ce', '6c619117-b941-4c47-9ed5-873cb647adcf', '2022-02-05', false, 0, 'Conservation_of_Leather_and_Related_Materials.pdf', 'Conservation of Leather and Related Materials', 'Marion Kite, Roy Thomson', 'The conservation of skin, leather and related materials is an area that, until now, has had little representation by the written word in book form. Marion Kite and Roy Thomson, of the Leather Conservation Centre, have prepared a text which is both authoritative and comprehensive, including contributions from the leading specialists in their fields, such as Betty Haines, Mary Lou Florian, Ester Cameron and Jim Spriggs. The book covers all aspects of Skin and Leather preservation, from Cuir Bouillie to Bookbindings. There is significant discussion of the technical and chemical elements necessary in conservation, meaning that professional conservators will find the book a vital part of their collection. As part of the Butterworth-Heinemann Black series, the book carries the stamp of approval of the leading figures in the world of Conservation and Museology, and as such it is the only publication available on the topic carrying this immediate mark of authority. * First book to cover the subject comprehensively * Wide coverage, including Fish and Reptiles, Taxidermy and Furs, making it invaluable for conservator, curator and collector alike * Technical aspects of conservation discussed in full');



















